Handle error during run-agl-postinsts
 * do not remove post install script if failed

Bug-AGL: SPEC-700

Change-Id: I1b45670ecbe3915a69cfa659031ac877eb794571
Signed-off-by: Ronan Le Martret <ronan.lemartret@iot.bzh>
Reviewed-on: https://gerrit.automotivelinux.org/gerrit/10025
Reviewed-by: José Bollo <jobol@nonadev.net>
Tested-by: Jenkins Job builder account <agl-jobbuilder@automotivelinux.org>
ci-image-build: Jenkins Job builder account <agl-jobbuilder@automotivelinux.org>
Reviewed-by: Jan-Simon Moeller <jsmoeller@linuxfoundation.org>
(cherry picked from commit 0c28379c6d8ab33f3c902b6617503ca634b8c90e)
Reviewed-on: https://gerrit.automotivelinux.org/gerrit/10091

diff --git a/meta-agl/recipes-devtools/run-agl-postinsts/run-agl-postinsts/run-agl-postinsts b/meta-agl/recipes-devtools/run-agl-postinsts/run-agl-postinsts/run-agl-postinsts
--- a/meta-agl/recipes-devtools/run-agl-postinsts/run-agl-postinsts/run-agl-postinsts
+++ b/meta-agl/recipes-devtools/run-agl-postinsts/run-agl-postinsts/run-agl-postinsts
@@ -23,10 +23,16 @@ exec_postinst_scriptlets() {
         [ "$POSTINST_LOGGING" = "1" ] && eval echo "Running postinst $i..." $append_log
         if [ -x $i ]; then
             eval sh -c $i $append_log
-            rm $i
+            if [ $? -eq 0 ]; then
+                rm $i
+            else
+                echo "ERROR: postinst $i failed."
+                [ "$POSTINST_LOGGING" = "1" ] && eval echo "ERROR: postinst $i failed." $append_log
+                remove_agl_pi_dir=0
+            fi
         else
-            echo "ERROR: postinst $i failed."
-            [ "$POSTINST_LOGGING" = "1" ] && eval echo "ERROR: postinst $i failed." $append_log
+            echo "ERROR: postinst $i do not exists or do not have execute permission."
+            [ "$POSTINST_LOGGING" = "1" ] && eval echo "ERROR: postinst $i do not exists or do not have execute permission." $append_log
             remove_agl_pi_dir=0
         fi
     done
